application:
  subdomain: meowmail
  multi_instance: false
  background_task: true
  oidc_redirect_path: /api/v1/auth/oidc/callback
  upstreams:
    - location: /
      backend: http://meowmail:8080/
  injects:
    - id: open-save-chooser
      on: browser
      when:
        - "/*"
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/lzc-file-chooser-inject.js
services:
  meowmail:
    # upstream: docker.io/czyt/meowmail:v0.2.0
    image: registry.lazycat.cloud/czyt/czyt/meowmail:298d558e6b3e13cf
    environment:
      - MEOWMAIL_AUTH_MODE=oidc
      - MEOWMAIL_OIDC_FIRST_USER_ADMIN=true
      - MEOWMAIL_OIDC_ISSUER=${LAZYCAT_AUTH_OIDC_ISSUER_URI}
      - MEOWMAIL_OIDC_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - MEOWMAIL_OIDC_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - MEOWMAIL_OIDC_REDIRECT_URL=https://${LAZYCAT_APP_DOMAIN}/api/v1/auth/oidc/callback
      - MEOWMAIL_VAULT_KEY={{ stable_secret "meowmail_vault_v1" }}
      - MEOWMAIL_DATA_DIR=/data
      - TZ={{ .U.timezone }}
    binds:
      - /lzcapp/var/data:/data
    user: "root"
    mem_limit: 512M
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - --show-error
        - http://127.0.0.1:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
